### ISSUE TITLE
getimagesize error show up issues

### ISSUE THREAD

**Issue by hypong** [moodlehq/moodle-docker#139]
All the images uploaded by me cant display correctly after I changed MOODLE_DOCKER_WEB_HOST from IP to **hostname.**
Then I changed it back from hostname to IP but the error still here.

here is my setting
```
#export MOODLE_DOCKER_WEB_HOST=xxx.xxx.com
export MOODLE_DOCKER_WEB_HOST=xxx.xxx.174.19
export MOODLE_DOCKER_WEB_PORT=0.0.0.0:8000
```

error message looks like this
```
Warning: getimagesize(/var/www/moodledata/filedir/67/3a/673a97eee2155bca600b3e630a2fac9c0fb521c6): failed to open stream: No such file or directory in /var/www/html/lib/filestorage/file_system.php on line 417
```

any idea?

**Comment by scara** [comment]
Hi @hypong,
did you know that the Moodle Docker Toolbox is for dev/test purposes?

For that reason, Moodle data storage is ephemeral i.e. when you change an ENV VAR and you are required to restart the compose, those data could be lost:
```yaml
version: "2"
services:
  webserver:
    image: "moodlehq/moodle-php-apache:${MOODLE_DOCKER_PHP_VERSION}"
    depends_on:
      - db
    volumes:
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/html"
      - "${ASSETDIR}/web/apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf"
    environment:
...
```
unless you change the current _compose_ setup to persist even "moodledata" in an external volume:
```yaml
...
    volumes:
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/html"
      - "/path/to/data:/var/www/moodledata"
      - "${ASSETDIR}/web/apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf"
    environment:
...
```

HTH,
Matteo
