### ISSUE TITLE
Automated testing for moodle-docker-compose.cmd

### ISSUE THREAD

**Issue by danpoltawski** [moodlehq/moodle-docker#56]
I did some experiments using appveyor to test this project on windows - but appveyor sadly doesn't support the docker environment. 

But moodle-docker-compose.cmd still gives me the spooks because I (and i'm sure many contributors) aren't working on windows with batch scripts much. 

I suggest that we create some test for the script - perhaps with a fake docker-compose fixture which echos flags and we can test the output to make sure it's doing what we expect.

**Comment by scara** [comment]
Hi @danpoltawski,
never used _appveyor_ (at least, 'till now) but they actually have an image w/ _docker_: https://www.appveyor.com/docs/build-environment/#pre-installed-software => `Visual Studio 2017`, confirmed even in the latest update, https://www.appveyor.com/updates/2017/09/04/.

See an example in https://stefanscherer.github.io/setup-windows-docker-ci-appveyor/.

HTH,
Matteo

**Comment by danpoltawski** [comment]
I don’t think it can run linux containers (can’t remember the details off top of head)

**Comment by danpoltawski** [comment]
Ah the build is still there: https://ci.appveyor.com/project/danpoltawski/docker-moodle/build/1.0.9#L29

**Comment by danpoltawski** [comment]
And [here is](https://github.com/moodlehq/moodle-docker/blob/35a9a6cde83db30e470aa86c28e520d1e2fd2166/appveyor.yml) the appveyor.yml I used for reference
```
version: 1.0.{build}
build: off
image: Visual Studio 2017

environment:
  MOODLE_DOCKER_DB: pgsql
  MOODLE_DOCKER_WWWROOT: c:\projects\moodle

install:
  - choco install docker-compose

test_script:
  - bin\moodle-docker-compose.cmd pull
```
